---
title: "Chapter4.1"
author: "高至彬"
date: "2020/4/13"
output: html_document
---

```{r}
vectorExample <- c("小明","小英","大雄")

# 有多少位置可選：
length(vectorExample)
```

```{r}
vectorExample[[1]]
vectorExample[[3]]
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```

```{r}
listExample[[1]]#小明
listExample[[2]]#整個學期
```

```{r}
library(jsonlite)
fromJSON("https://data.tainan.gov.tw/dataset/4cd9345a-04bf-4328-a97d-314ff78b4763/resource/afc025fc-1ef4-447c-b785-a680391d0ca1/download/tnsport2.json", simplifyDataFrame = F) -> tainanSportsMap
```
```{r}
tainanSportsMap[[4]]
```

```{r}
# 有多少名字可選：
names(listExample)
```
```{r}
listExample$student #不用雙引號
listExample$`學期` # 特殊命名依然要用反頓點呼叫
```

```{r}
str(listExample)
```




